sudo: required
services:
  - docker

before_install:
  - docker build -t pavan/kp -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pavan/kp npm run test -- --coverage

after_success:
  - docker build -t pavanleton/multi-client ./client
  - docker build -t pavanleton/multi-nginx ./nginx
  - docker build -t pavanleton/multi-server ./server
  - docker build -t pavanleton/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push pavanleton/multi-client
  - docker push pavanleton/multi-nginx
  - docker push pavanleton/multi-server
  - docker push pavanleton/multi-worker
#blaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
