sudo: required
services:
  - docker

before_install:
  - docker build -t pavan/kp -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pavan/kp npm run test -- --coverage

after_success:
  - docker build -t pavan/multi-client ./client
  - docker build -t pavan/multi-nginx ./nginx
  - docker build -t pavan/multi-server ./server
  - docker build -t pavan/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker tag pavan/multi-client pavanleton/multi-learning:client
  - docker push pavanleton/multi-learning:client
  - docker tag pavan/multi-nginx pavanleton/multi-learning:nginx
  - docker push pavanleton/multi-learning:nginx
  - docker tag pavan/multi-server pavanleton/multi-learning:server
  - docker push pavanleton/multi-learning:server
  - docker tag pavan/multi-worker pavanleton/multi-learning:worker
  - docker push pavanleton/multi-learning:worker
#blaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
